Adds status color to commandline

diff --git a/DotFiles/bashrc b/DotFiles/bashrc
--- a/DotFiles/bashrc
+++ b/DotFiles/bashrc
@@ -164,6 +164,15 @@ BG_LIGHT_CYAN="\e[106m"
 BG_WHITE="\e[107m"
 
 # Prompt Config
+
+# Get color for exit status
+function exit_status() {
+    STATUS=`echo $?`
+    if [ ! "${STATUS}" == "0" ]; then
+        echo -e $LIGHT_RED
+    fi
+}
+
 # get current branch in git repo
 function parse_git_branch() {
     if [ -d ".git" ]; then
@@ -202,4 +211,4 @@ function parse_git_status_color {
     echo $color
 }
 
-export PS1="\e[96m>> CODE\e[0m\e[97mPOET\e[0m:\`parse_git_branch\`\e[0m\e[96m | \e[0m"
+export PS1="\e[96m\`exit_status\`>> CODE\e[0m\e[97mPOET\e[0m:\`parse_git_branch\`\e[0m\e[96m | \e[0m"
